version: "3.7"

services:
  backend:
    container_name: python
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -u backend/src/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  frontend:
    container_name: angular
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
